# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fb0a953e9d80b9fe14ce1e098196641cbe17c97c6947377c1e8aeefad89296c9019920fe9361d838983d6354ad1b766c146e9a948c53562990089af993ce429

test:
  secret_key_base: 4fe775ecac5ca7a39e2af0a843a443a335ee1f6d6e0298ec6046b54d80210dae0bf7ae4dcb4312aeccdaaa501607cc5b28a4fdd92b3bf045586dc1a2f1a4d64b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
